package org.metavacua.categoricalreasoner.citation;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.stream.Collectors;

/**
 * BibLaTeX 3.0 exporter.
 * Converts citation records to BibLaTeX format for TeX bibliography generation.
 * <p>
 * Generates BibLaTeX entries that conform to:
 * - BibLaTeX 3.0 specification
 * - BibTeX standard fields
 * - Custom fields for formalization status
 */
public class BiblatexExporter {

    private static final String BIBLATEX_FILE = "references.bib";
    private static final String OUTPUT_DIR = "docs/dissertation";

    /**
     * Main method for standalone execution.
     */
    public static void main(String[] args) {
        try {
            generate();
            System.out.println("BibLaTeX file generated successfully");
        } catch (Exception e) {
            System.err.println("Error generating BibLaTeX file: " + e.getMessage());
            e.printStackTrace();
            System.exit(1);
        }
    }

    /**
     * Generates BibLaTeX file from citation repository.
     *
     * @throws IOException if unable to write output file
     */
    public static void generate() throws IOException {
        StringBuilder bibtex = new StringBuilder();

        // Add header
        bibtex.append("% BibLaTeX bibliography generated from citation repository\n");
        bibtex.append("% Generated by: org.metavacua.categoricalreasoner.citation.BiblatexExporter\n");
        bibtex.append("% DO NOT EDIT MANUALLY - Changes will be overwritten\n");
        bibtex.append("\n");

        // Add all citations
        List<Citation> citations = CitationRepository.getAll();

        // Sort by key for consistency
        citations = citations.stream()
            .sorted((a, b) -> a.key().value().compareTo(b.key().value()))
            .toList();

        for (Citation citation : citations) {
            bibtex.append(toBiblatexEntry(citation));
            bibtex.append("\n");
        }

        // Write to file
        Path outputPath = Paths.get(OUTPUT_DIR, BIBLATEX_FILE);
        Files.createDirectories(outputPath.getParent());
        Files.writeString(
            outputPath,
            bibtex.toString(),
            StandardOpenOption.CREATE,
            StandardOpenOption.TRUNCATE_EXISTING
        );

        System.out.println("BibLaTeX file written to: " + outputPath);
    }

    /**
     * Converts a citation to BibLaTeX entry.
     */
    private static String toBiblatexEntry(Citation citation) {
        StringBuilder entry = new StringBuilder();

        String entryType = mapWorkTypeToBiblatex(citation.type());
        String key = citation.key().value();

        entry.append("@").append(entryType).append("{").append(key).append(",\n");

        // Title
        entry.append("  title = {").append(escapeLaTeX(citation.title().text())).append("},\n");

        // Author(s)
        String authors = citation.authors().stream()
            .map(BiblatexExporter::formatAuthor)
            .collect(Collectors.joining(" and "));
        entry.append("  author = {").append(authors).append("},\n");

        // Year
        entry.append("  year = {").append(citation.date().year()).append("}");

        // Optional month if available
        citation.date().month().ifPresent(month ->
            entry.append(",\n  month = {").append(monthName(month)).append("}")
        );

        // DOI
        citation.doi().ifPresent(doi ->
            entry.append(",\n  doi = {").append(doi.value()).append("}")
        );

        // URL (prefer DOI, then arXiv, then Wikidata)
        citation.doi().map(Doi::url).ifPresentOrElse(
            url -> entry.append(",\n  url = {").append(url).append("}"),
            () -> citation.arxiv().map(ArxivId::url).ifPresentOrElse(
                url -> entry.append(",\n  url = {").append(url).append("}"),
                () -> citation.wikidata().map(Qid::url).ifPresent(
                    url -> entry.append(",\n  url = {").append(url).append("}")
                )
            )
        );

        // Formalization status (custom field)
        entry.append(",\n  formalizationstatus = {").append(citation.status().name().toLowerCase()).append("}");

        // Agent context (custom field)
        citation.agentContext().ifPresent(context -> {
            context.category().ifPresent(cat ->
                entry.append(",\n  category = {").append(escapeLaTeX(cat)).append("}")
            );
            context.notes().ifPresent(notes ->
                entry.append(",\n  agentnotes = {").append(escapeLaTeX(notes)).append("}")
            );
        });

        // Dependencies (custom field)
        if (!citation.dependsOn().isEmpty()) {
            String deps = citation.dependsOn().stream()
                .map(CitationKey::value)
                .collect(Collectors.joining(","));
            entry.append(",\n  dependencies = {").append(deps).append("}");
        }

        entry.append("\n}\n");

        return entry.toString();
    }

    /**
     * Formats a Person for BibLaTeX author field.
     */
    private static String formatAuthor(Person person) {
        StringBuilder sb = new StringBuilder();

        person.givenName().ifPresent(gn -> {
            sb.append(gn);
            sb.append(" ");
        });

        person.particle().ifPresent(p -> {
            sb.append(p);
            sb.append(" ");
        });

        sb.append(person.familyName());

        person.suffix().ifPresent(s -> {
            sb.append(", ");
            sb.append(s);
        });

        return sb.toString();
    }

    /**
     * Maps WorkType to BibLaTeX entry type.
     */
    private static String mapWorkTypeToBiblatex(WorkType type) {
        return switch (type) {
            case ARTICLE -> "article";
            case BOOK -> "book";
            case CONFERENCE -> "inproceedings";
            case INCOLLECTION -> "incollection";
            case THESIS -> "phdthesis";
            case REPORT -> "techreport";
            case PREPRINT -> "misc";
        };
    }

    /**
     * Converts month number to BibLaTeX month name.
     */
    private static String monthName(int month) {
        return switch (month) {
            case 1 -> "jan";
            case 2 -> "feb";
            case 3 -> "mar";
            case 4 -> "apr";
            case 5 -> "may";
            case 6 -> "jun";
            case 7 -> "jul";
            case 8 -> "aug";
            case 9 -> "sep";
            case 10 -> "oct";
            case 11 -> "nov";
            case 12 -> "dec";
            default -> "";
        };
    }

    /**
     * Escapes special LaTeX characters.
     */
    private static String escapeLaTeX(String text) {
        return text
            .replace("\\", "\\textbackslash{}")
            .replace("&", "\\&")
            .replace("%", "\\%")
            .replace("$", "\\$")
            .replace("#", "\\#")
            .replace("_", "\\_")
            .replace("{", "\\{")
            .replace("}", "\\}")
            .replace("~", "\\textasciitilde{}")
            .replace("^", "\\textasciicircum{}");
    }
}
